# Generated by Django 3.1.7 on 2021-04-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioName', models.CharField(max_length=100)),
                ('portfolioClient', models.CharField(max_length=150)),
                ('portfolioImageOne', models.ImageField(upload_to='pics')),
                ('portfolioImageTwo', models.ImageField(upload_to='pics')),
                ('portfolioImageThree', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('portfolioCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photatoes.category')),
            ],
        ),
    ]
