# Generated by Django 3.1.7 on 2021-04-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photatoes', '0002_contactlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactlist',
            new_name='Contact',
        ),
    ]
