# Generated by Django 3.1.7 on 2021-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photatoes', '0004_auto_20210409_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageAperture',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
