# Generated by Django 3.1.7 on 2021-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photatoes', '0006_portfolio_portfoliophotographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='photographerProfilePic',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
